spring:
  application:
    name: apigwx
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMERX
          predicates:
            - Path=/api/v1/customers/**
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
