spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://host.docker.internal:9411/     # the docker container is talking back to real host, as localhost would refer to the container itself
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false


